routes/homepage.py
from flask import (
    render_template,
    Blueprint,
)

from routes import current_user

from models.topic import Topic
from models.user import User
from models.reply import Reply

main = Blueprint('sx_homepage', __name__)


@main.route('/<int:id>')
def index(id):
    u = User.one(id=id)
    t1 = Topic.all(user_id=id)
    t = list(reversed(t1))
    r1 = Reply.all(user_id=id)
    r = list(reversed(r1))
    topic = []
    for each in r:
        one = Topic.one(id=each.topic_id)
        topic.append(one)
    return render_template("homepage.html", user=u, topic=t, topic2=topic)

routes/setting.py
import os
import uuid


from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.user import User
from werkzeug.datastructures import FileStorage


main = Blueprint('setting', __name__)


@main.route("/")
def index():
    user = current_user()
    token = new_csrf_token()
    return render_template("setting.html", user=user, token=token)


@main.route("/name", methods=["POST"])
@csrf_required
def name():
    token = new_csrf_token()
    user = current_user()
    form = request.form
    User.update(id=user.id, username=form['username'], sign=form['sign'])
    u = User.one(id=user.id)
    return render_template("setting.html", user=u, token=token)


@main.route("/password", methods=["POST"])
@csrf_required
def password():
    token = new_csrf_token()
    user = current_user()
    form = request.form
    old = User.salted_password(form['old_pass'])
    new = User.salted_password(form['new_pass'])
    if User.one(id=user.id, password=old) is not None:
        User.update(id=user.id, password=new)
        u = User.one(id=user.id)
    else:
        return redirect(url_for('index.index'))

    return render_template("setting.html", user=u, token=token)


@main.route("/avatar", methods=["POST"])
@csrf_required
def avatar():
    token = new_csrf_token()
    file: FileStorage = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)
    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))
    u = User.one(id=u.id)
    return render_template("setting.html", user=u, token=token)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    user = current_user()
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", user=user, ms=ms, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css">
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <ul class="nav pull-right">
                    <li><a href='{{ url_for('topic.index') }}'>首页</a></li>
                    <li><a href="/setting">设置</a></li>
                    <li><a href='/logout'>退出</a></li>
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
        </div>
    </div>

    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>

                <div class="inner">
                    <div class="user_card">
                        <div>
                            <a class="user_avatar" href="{{ url_for('sx_homepage.index', id=user.id) }}">
                                <img src="{{ user.image }}" title="{{ user.username }}">
                            </a>
                            <span class="user_name"><a class="dark" href="{{ url_for('sx_homepage.index', id=user.id) }}">{{ user.username }}</a></span>

                            <div class="space clearfix"></div>
                            <span class="signature">
                                {{ user.sign }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel">
                <div class="inner">
                    <a href="/topic/new?board_id=1" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>

            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src=" {{ user.image }} " class="user_avatar">
                </div>
                <a class="dark">{{ user.username }}</a>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            {% for t in topic %}
            <div class="cell">
                <a class="user_avatar pull-left" href="{{ url_for('sx_homepage.index', id=t.user_id) }}">
                    <img src=" {{ user.image }} " title="sxuni">
                </a>

                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.reply_count() }}
                    </span>

                    <span class="count_seperator">/</span>

                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                    </span>
                </span>

                <a class="last_time pull-right" href="{{ url_for('topic.detail', id=t.id) }}">
                    <img class="user_small_avatar" src=" {{ t.reply_image() }} ">
                    <span class="last_active_time">{{ t.created_time | format_time }}</span>
                </a>

                <div class="topic_title_wrapper">
                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                        {{ t.title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>

            {% for t2 in topic2 %}
            <div class="cell">
                <a class="user_avatar pull-left" href="{{ url_for('sx_homepage.index', id=t2.user_id) }}">
                    <img src=" {{ t2.topic_image() }} " title="wallmama">
                </a>

                <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t2.reply_count() }}
                    </span>

                    <span class="count_seperator">/</span>

                    <span class="count_of_visits" title="点击数">
                        {{ t2.views }}
                    </span>
                </span>


                <a class="last_time pull-right" href="{{ url_for('topic.detail', id=t2.id) }}">
                    <img class="user_small_avatar" src=" {{ t2.reply_image() }} ">
                    <span class="last_active_time">{{ t2.created_time | format_time }}</span>
                </a>

                <div class="topic_title_wrapper">
                    <a class="topic_title" href="{{ url_for('topic.detail', id=t2.id) }}" title="{{ t2.title }}">
                    {{ t2.title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.15.0/themes/prism.css">
    <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
<head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    <li><a href="/signup" target="">注册</a></li>
                    <li><a href="/signin">登录</a></li>
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
        </div>
    </div>

    <div id="main">
        <div id="sidebar">
              <div class="panel">
                  <div class="inner">
                      <p>elpsx的论坛</p>
                      <div>
                          您可以
                          <a href="/signin">登录</a>
                          或
                          <a href="/signup">注册</a>
                          <div>
                          测试账号
                          aaa
                          密码
                          123
                          </div>
                      </div>
                  </div>
              </div>
        </div>

        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic"
                       class="topic-tab current-tab">
                        全部的帖子
                    </a>

                    {% for b in bs %}
                    <a href="/topic?board_id={{ b.id }}"
                       class="topic-tab current-tab">
                        {{ b.title }}
                    </a>
                    {% endfor %}
                </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <a class="user_avatar pull-left" href="{{ url_for('sx_homepage.index', id=t.user_id) }}">
                                <img src="{{ t.user_id | image1 }}" title="{{ t.user_id | name1 }}">
                            </a>

                            <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                    {{ t.replies() | count }}
                                </span>

                                <span class="count_seperator">/</span>

                                <span class="count_of_visits" title="点击数">
                                    {{ t.views }}
                                </span>
                            </span>

                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>

                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
<h1>用户资料页面</h1>
<div>
    {{ user.id }}
</div>
<div>
    {{ user.username }}
</div>

<div>
    <div>创建的</div>
    {% for t in created %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>
<div>
    <div>参与的</div>
    {% for t in replied %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>

<form method="post"
      action="{{ url_for('.avatar_add')}}"
      enctype="multipart/form-data"
>
    <input type="file" name="avatar">
    <button type="submit">上传头像</button>
</form>

<img src="{{ user.image }} ">

</body>
</html>

templates/setting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css" media="all">
    <title>用户设置</title>
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <ul class="nav pull-right">
                    <li><a href='{{ url_for('topic.index') }}'>首页</a></li>
                    <li><a href="/setting">设置</a></li>
                    <li><a href='/logout'>退出</a></li>
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
        </div>
    </div>

    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>

                <div class="inner">
                    <div class="user_card">
                        <div>
                            <a class="user_avatar" href="{{ url_for('sx_homepage.index', id=user.id) }}">
                                <img src="{{ user.image }}" title="{{ user.username }}">
                            </a>
                            <span class="user_name"><a class="dark" href="{{ url_for('sx_homepage.index', id=user.id) }}">{{ user.username }}</a></span>

                            <div class="space clearfix"></div>
                            <span class="signature">
                                {{ user.sign }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel">
                <div class="inner">
                    <a href="/topic/new?board_id=1" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li><a href="/">主页</a><span class="divider">/</span></li>
                        <li class="active">设置</li>
                    </ul>
                </div>

                <div class="inner">
                    <form id="setting_form" class="form-horizontal" action="{{ url_for('setting.name', token=token, id=user.id)}}" method="post">
                        <div class="control-group">
                            <label class="control-label" for="name">用户名</label>

                            <div class="controls">
                                <input class="input-xlarge readonly" id="name" name="username" size="30" type="text" value="{{ user.username }}">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="signature">个性签名</label>

                            <div class="controls">
                                <textarea class="input-xlarge" id="signature" name="sign" size="30"></textarea>
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">更改密码</span>
                </div>
                <div class="inner">
                    <form id="change_pass_form" class="form-horizontal" action="{{ url_for('setting.password', token=token) }}" method="post">
                        <div class="control-group">
                            <label class="control-label" for="old_pass">当前密码</label>

                            <div class="controls">
                                <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="new_pass">新密码</label>

                            <div class="controls">
                                <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">上传头像</span>
                </div>
                <div class="inner">
                    <div class="form-actions">
                        <form method="post" action="{{ url_for('setting.avatar', token=token) }}" enctype="multipart/form-data">
                            <input type="file" name="avatar">
                            <button class="span-primary submit_btn" type="submit">上传头像</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css">
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    <li><a href="/signup" target="">注册</a></li>
                    <li><a href="/signin">登录</a></li>
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
        </div>
    </div>

    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">关于</span>
                </div>

                <div class="inner">
                    <p>elpsx的论坛</p>
                    <p>在这里你可以：</p>
                      <ul>
                        <li>发表你的看法</li>
                        <li>提出你的问题</li>
                        <li>分享你的知识</li>
                      </ul>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li><a href="/">主页</a><span class="divider">/</span></li>
                        <li class="active">登录</li>
                    </ul>
                </div>

                <div class="inner">
                    <form id="signin_form" class="form-horizontal" action="{{ url_for('.login') }}" method="post">
                        <div class="control-group">
                            <label class="control-label" for="name">用户名</label>

                            <div class="controls">
                                <input class="input-xlarge" name="username" size="30" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="pass">密码</label>
                            <div class="controls">
                                <input class="input-xlarge" name="password" size="30" type="password">
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary" value="登录">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css">
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">

                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    <li><a href="/signup" target="">注册</a></li>
                    <li><a href="/">登录</a></li>
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
        </div>
    </div>

    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">关于</span>
                </div>

                <div class="inner">
                    <p>elpsx的论坛</p>
                    <p>在这里你可以：</p>
                      <ul>
                        <li>发表你的看法</li>
                        <li>提出你的问题</li>
                        <li>分享你的知识</li>
                      </ul>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li><a href="/">主页</a><span class="divider">/</span></li>
                        <li class="active">注册</li>
                    </ul>
                </div>

                <div class="inner">
                    <form id="signin_form" class="form-horizontal" action="{{ url_for('.register') }}" method="post">
                        <div class="control-group">
                            <label class="control-label" for="name">用户名</label>

                            <div class="controls">
                                <input class="input-xlarge" name="username" size="30" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="pass">密码</label>
                            <div class="controls">
                                <input class="input-xlarge" name="password" size="30" type="password">
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary" value="注册">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>